result
ADIGrimm/online-bookstore pull request #1
Opened 2024-09-29 11:22 UTC by ADIGrimm

2024-10-01 11:36 UTC, Elena-Bruyako requested changes
see comments

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/OnlineBookstoreApplication.java
> +@EntityScan(basePackages = "online.bookstore.model")
remove

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/OnlineBookstoreApplication.java
> +            bookService.save(book);
call also findAll method

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/Book.java
> +@Entity
```suggestion
@Entity
@Getter
@Setter
@Table(name...
```

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/Book.java
> +    public Long getId() {
remove gettes and setters, you can use Lombok annotations for them

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/repository/impl/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't add a book to db: " + book, e);
```suggestion
            throw new DataProcessingException("Can't add a book to db: " + book, e);
```

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't get list of all books" + e);
```suggestion
            throw new DataProcessingException("Can't get list of all books" + e);
```

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-10-01 11:36 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/BookServiceImpl.java
> +    }
```suggestion
```

2024-10-04 10:49 UTC, sarakhmen approved these changes

2024-10-05 07:52 UTC, merged