Category implementation
ADIGrimm/online-bookstore pull request #10
Opened 2024-10-29 07:33 UTC by ADIGrimm

2024-10-29 14:31 UTC, Elena-Bruyako requested changes
see comments

2024-10-29 14:31 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/CategoryController.java
> +@RequestMapping("/categories")
Add Swagger annotations

2024-10-29 14:31 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/CategoryController.java
> +    public List<CategoryDto> getAll() {
You can add Pageable and return Page instead of List

2024-10-29 14:31 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/dto/book/CreateBookRequestDto.java
> +    @NotNull
```suggestion
    @NotEmpty
```

2024-10-29 14:31 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/Category.java
> +    @NotNull
```suggestion
    @Column(nullable = false, unique = true)
```

2024-10-29 14:31 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(categoryRepository
bad practice to call several methods inline
create local variable

2024-10-29 14:31 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/CategoryServiceImpl.java
> +        category = categoryRepository.save(category);
```suggestion
        categoryRepository.save(category);
```

2024-10-29 14:31 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +                  type: varchar(255)
add unique constraint

2024-10-30 11:25 UTC, ahoienko approved these changes
Good job!

2024-10-30 12:58 UTC, Elena-Bruyako approved these changes

2024-10-30 14:44 UTC, merged