order implementation
ADIGrimm/online-bookstore pull request #12
Opened 2024-11-06 16:07 UTC by ADIGrimm

2024-11-06 18:23 UTC, Elena-Bruyako requested changes
see cooments

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/OrderController.java
> +    public Page<OrderDto> getAll(Authentication authentication, Pageable pageable) {
you can add
```suggestion
    public Page<OrderDto> getAll(Authentication authentication, @ParameterObject @PageableDefault Pageable pageable) {
```

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/OrderController.java
> +    public OrderDto createOrder(Authentication authentication, @RequestBody String address) {
It's better to create Dto

```suggestion
    public OrderDto createOrder(Authentication authentication, @RequestBody @Valid CreateOrderRequestDto orderDto) {
```

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/OrderController.java
> +    public OrderDto updateStatus(@PathVariable Long orderId, @RequestBody Order.Status status) {
same here

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/OrderItemController.java
> +public class OrderItemController implements UserContextHelper {
remove controller, all endpoints should be in OrderController

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/Order.java
> +        Pending,
use upper case only for enum

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/OrderItem.java
> +    @OneToOne
Add lazy and joincolumn

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/OrderItemServiceImpl.java
> +public class OrderItemServiceImpl implements OrderItemService {
remove, replace logic to OrderService

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/OrderServiceImpl.java
> +    @Override
think where is Transactional needed

2024-11-06 18:23 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/OrderServiceImpl.java
> +        order.setOrderItems(shoppingCartRepository.findById(userId).get().getCartItems().stream()
shop cart could be empty
improve readability

2024-11-08 09:54 UTC, Elena-Bruyako requested changes
one comment

2024-11-08 09:54 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/OrderServiceImpl.java
> +            throw new RuntimeException("Shopping cart is empty: " + cartItems);
```suggestion
            throw new OrderProcessingException("Shopping cart is empty for user " + userId);
```

2024-11-08 13:58 UTC, ahoienko approved these changes
Good job!

2024-11-14 15:48 UTC, merged