Book and Category tests implementation
ADIGrimm/online-bookstore pull request #14
Opened 2024-11-20 15:54 UTC by ADIGrimm

2024-11-21 07:23 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-11-21 07:23 UTC, liliia-ponomarenko commented on src/test/java/online/bookstore/book/BookControllerTest.java
> +    private JwtUtil jwtUtil;
Why do you need it?

2024-11-21 07:23 UTC, liliia-ponomarenko commented on src/test/java/online/bookstore/book/BookControllerTest.java
> +    @Transactional
if your test doesn’t work without this annotation `@SqlMergeMode(SqlMergeMode.MergeMode.MERGE)` can help you

2024-11-21 07:23 UTC, liliia-ponomarenko commented on src/test/java/online/bookstore/book/BookControllerTest.java
> +        expected.setCategories(requestBook.getCategories());
better move such logic to the private method or util class and simplify your test cases.

2024-11-21 07:23 UTC, liliia-ponomarenko commented on src/test/java/online/bookstore/book/BookServiceTest.java
> +        List<Book> books = List.of(new Book(), new Book());
better initialize books. Also, I recommend you use Given-When-Than pattern

2024-11-21 07:23 UTC, liliia-ponomarenko commented on src/test/java/online/bookstore/category/CategoryControllerTest.java
> +class CategoryControllerTest {
the same comments

2024-11-21 17:35 UTC, ADIGrimm commented on src/test/java/online/bookstore/book/BookControllerTest.java
> +    private JwtUtil jwtUtil;
Because tests fail without jwt.secret, which i don't know how to fix

2024-11-22 08:54 UTC, okuzan approved these changes

2024-11-23 13:07 UTC, merged