Data jpa and another
ADIGrimm/online-bookstore pull request #3
Opened 2024-10-09 12:38 UTC by ADIGrimm

2024-10-09 14:39 UTC, Elena-Bruyako requested changes
see comments

2024-10-09 14:39 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/BookController.java
> +    public void delete(@PathVariable Long id) {
add update implementation

2024-10-09 14:39 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/repository/BookRepository.java
> +@Repository
```suggestion
```

2024-10-10 07:18 UTC, liliia-ponomarenko requested changes
Good job! A few comments ;)

2024-10-10 07:18 UTC, liliia-ponomarenko commented on src/main/java/online/bookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
```suggestion
```
It is the default response status.

2024-10-10 07:18 UTC, liliia-ponomarenko commented on src/main/java/online/bookstore/service/impl/BookServiceImpl.java
> +        book.setCoverImage(bookRequestDto.getCoverImage());
use mapper (mapstruct) for this logic

2024-10-10 07:18 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
add one empty line at the end of the file ;)

2024-10-10 14:44 UTC, Elena-Bruyako requested changes
see comments

2024-10-10 14:44 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/BookController.java
> +    public void update(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
```suggestion
    public BookDto update(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
```

2024-10-10 14:44 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/Book.java
> +    @Column(name = "is_deleted", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-10-11 09:56 UTC, ahoienko approved these changes
Good job!

2024-10-12 10:38 UTC, merged