User implementation
ADIGrimm/online-bookstore pull request #7
Opened 2024-10-20 12:45 UTC by ADIGrimm

2024-10-20 17:59 UTC, Elena-Bruyako requested changes
see comments

2024-10-20 17:59 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/User.java
> +    @Column(unique = true)
```suggestion
    @Column(unique = true, nullable = false)
```

2024-10-20 17:59 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/User.java
> +    @Column(columnDefinition = "TINYINT(1)")
same here
be consistent, don't need to use different validation annotations

2024-10-20 17:59 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/Book.java
> +    @Column(columnDefinition = "TINYINT(1)")
```suggestion
    @Column(columnDefinition = "TINYINT(1)", nullable = false)
```

2024-10-20 17:59 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/model/Book.java
> +    @NotNull
```suggestion
```

2024-10-21 08:45 UTC, okuzan approved these changes

2024-10-21 08:45 UTC, okuzan commented on src/main/java/online/bookstore/model/User.java
> +@SQLRestriction("is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE users SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction("is_deleted = FALSE")
```

2024-10-22 12:08 UTC, merged