Spring Boot Security implementation
ADIGrimm/online-bookstore pull request #8
Opened 2024-10-23 21:07 UTC by ADIGrimm

2024-10-24 06:36 UTC, liliia-ponomarenko requested changes
Good job! A few minor comments ;)

2024-10-24 06:36 UTC, liliia-ponomarenko commented on src/main/java/online/bookstore/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
In your solution, the user-role has many-to-many relations. You give a USER role by default to each registered user, meaning that ADMIN also has a USER role. So you can use only the USER role here  
```suggestion
    @PreAuthorize("hasAnyRole('ROLE_USER')")
```

2024-10-24 06:36 UTC, liliia-ponomarenko commented on src/main/java/online/bookstore/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
the same (check other endpoint’s)

2024-10-24 06:36 UTC, liliia-ponomarenko commented on src/main/java/online/bookstore/model/Role.java
> +
```suggestion
```
only one empty line

2024-10-24 06:36 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/07-create-association-role-for-admin.yaml
> +                  value: 2
add one empty line

2024-10-24 13:24 UTC, Elena-Bruyako requested changes
one comment

2024-10-24 13:24 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/UserServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Can't find role"))));
wrong exception

2024-10-24 14:45 UTC, Elena-Bruyako requested changes

2024-10-24 14:45 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/UserServiceImpl.java
> +                .orElseThrow(() -> new RegistrationException("Can't find role"))));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Can't find role"))));
```

2024-10-24 14:45 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/service/impl/UserServiceImpl.java
>      public UserResponseDto registration(UserRegistrationRequestDto requestDto) {
```suggestion
    public UserResponseDto registration(UserRegistrationRequestDto requestDto) {
        if (userRepo.existsByEmail(request.email())) {
            throw new RegistrationException(
                    String.format("User with this email: %s already exists", request.email())
            );
        }
```

2024-10-25 07:48 UTC, ahoienko approved these changes
Good job!

2024-10-26 12:06 UTC, merged