jwt implementation
ADIGrimm/online-bookstore pull request #9
Opened 2024-10-26 16:28 UTC by ADIGrimm

2024-10-26 16:38 UTC, Elena-Bruyako requested changes
see comments

2024-10-26 16:38 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
```suggestion
    public UserLoginResponseDto login(@RequestBody @Valid UserLoginRequestDto requestDto) {
```

2024-10-26 16:38 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/controller/AuthenticationController.java
> +    @PostMapping("/login")
Add Swagger annotations

2024-10-26 16:38 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/dto/user/UserLoginRequestDto.java
> +public record UserLoginRequestDto(String email, String password) {
add validation

2024-10-26 16:38 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-10-26 16:38 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(constant.length());
```

2024-10-26 16:38 UTC, Elena-Bruyako commented on src/main/java/online/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
create constant for `"Bearer "`

2024-10-26 16:38 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +jwt.expiration=300000
don't forget to add these properties to test/app.properties

2024-10-28 08:13 UTC, liliia-ponomarenko approved these changes
Great job!

2024-10-28 08:13 UTC, liliia-ponomarenko commented on src/main/java/online/bookstore/security/JwtAuthenticationFilter.java
> +    public static final String TOKEN_TYPE = "Bearer ";
```suggestion
    private static final String TOKEN_TYPE = "Bearer ";
```

2024-10-28 15:18 UTC, merged